build : 
	docker build -t centos .
run : 
	docker run -it --name centos /bin/bash
exec : 
	docker exec -it centos /binbash
ps : 
	docker ps -a
img : 
	docker images
rm : 
	docker rm centos
rmi : 
	docker rmi centos:centos7
