# base images
FROM ubuntu:latest

# RUN command
RUN echo Hello~ Its shell type command.
RUN ["echo","Hello~ Itss exec type command."]
RUN ["/bin/bash", "-c","echo 'Hello~ Its /bin/bash execution in shell type command.'"]
