#base images
FROM ubuntu:latest

#Run Command
RUN echo Hello~ It's shell type command.
RUN ["echo","Hello~ It's shell type command."]
RUN ["/bin/bash","-c","echo 'Hello~ Its /bin/bash execution in shell type command.'"]
